### PR TITLE
fix conflict of prs #5 #9

### PR DESCRIPTION
**Pull request by tparnell8**
PR's #5  and #9 had conflicting results, when #9 was merged in, it removed the use of the template in #5 

I'm no puppet-master so this was as elegant of a fix as I could come up with, but if someone has any suggestions where things could be more elegant...I am all ears.

### CODE REVIEW

**Comment by tparnell8** [comment]
*bump*...

**Comment by duchatran** [comment]
@tparnell8 : Just merged #11. You might need to resolve some conflicts with this pull.

**Comment by tparnell8** [comment]
@duchatran will do

**Comment by tparnell8** [comment]
@duchatran I just pushed...

**Comment by duchatran** [comment]
Thanks!

**Pull request merged**
